name: Build and deploy APIs with load test
on:
  workflow_dispatch:
env:
  app-name: "devops-k6-loadtest"
  rg-name: "rg-devops-k6-loadtest"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/loadtestapi
  deploy:
    runs-on: ubuntu-latest
    outputs:
      webapp-url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-name }}
          slot-name: 'staging'
          package: .
  loadtest:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Run LoadTests
        uses: k6io/action@v0.1
        with:
          filename: './loadtests/script.js'
          flags: -e API_BASEURL=${{ needs.deploy.outputs.webapp-url }} TESTRESULT_FILENAME=Results