# This is a basic workflow to showcase the use of Reusable Workflows
name: Node API
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
  deploy:
    uses: GTRekter/Template/.github/workflows/ReusableWorkflow_Azure.yml@main
    environment:
      name: 'Production'
    with:
      image_name: nodeapi
      tag: $GITHUB_RUN_NUMBER
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure_resource_group: ${{ secrets.AZURE_RESOURCE_GRUP }}
      azure_webapp: ${{ secrets.AZURE_WEBAPP }}
      registry: ${{ secrets.AZURE_REGISTRY }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}