name: Sample
on:
 workflow_dispatch:
jobs:
  test:
    uses: GTRekter/Training/.github/workflows/ReusableWorkflow_CodeQL.yml@main
    with:
      languageJson: '[{"language": ["csharp", "javascript"]}'